services:
  googlephotos_uploader:
    image: xportu/googlephotos_uploader:latest
    container_name: googlephotos_uploader
    restart: unless-stopped

    environment:
      - WATCHED_FOLDER=/data
      - AUTH_DATA=INSERT_YOUR_AUTH_DATA_HERE
      - LOG_PATH=/logs
      - TZ=Europe/Madrid

    volumes:
      -  INSERT_YOUR_PHOTO_FOLDER_HERE:/data
      -  INSERT_YOUR_LOG_FOLDER_HERE:/logs

    # If necessary, specify the UID/GID of the user for file permissions
    # user: "1000:1000"
